---
title: "Econ Assignment 4"
author: "Quin Smith"
date: "5/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(ggpubr)
library(patchwork)
```

```{r}
#read data
dam <- read.csv(here("data/damages.csv"))
warm <- read.csv("data/warming.csv")
```

```{r}
#Question 1
#dam^2
dam <- dam %>% 
  mutate(warm2 = warming^2)

#dam_lm
dam_lm <- lm(damages ~ warming + warm2, data=dam)

dam_lm[["coefficients"]][["(Intercept)"]] <- 0

#plot
dam_plot <- ggplot(data=dam) +
  geom_point(aes(x=warming, y=damages)) +
  stat_smooth(data=dam_lm, aes(x=warming, y=damages)) +
  theme_bw()

dam_plot
```

```{r}
#Question 2
x <-dam_lm[["coefficients"]][["warming"]]
x2 <-dam_lm[["coefficients"]][["warm2"]]
int <-dam_lm[["coefficients"]][["(Intercept)"]]

warm <- warm %>% 
  mutate(dam_base = (warming_baseline*x) + ((warming_baseline)^2*x2) + int,
         dam_pulse = (warming_pulse*x) + ((warming_pulse)^2*x2) + int,
         dam_diff = dam_pulse - dam_base,
         dam_ton = dam_diff/35000000000)

#graphs
dam_base_plot <- ggplot(data = warm) +
  geom_point(aes(x=year, y=dam_base)) +
  theme_bw()

dam_pulse_plot <- ggplot(data = warm) +
  geom_point(aes(x=year, y=dam_pulse)) +
  theme_bw()

dam_diff_plot <- ggplot(data = warm) +
  geom_point(aes(x=year, y=dam_diff)) +
  theme_bw()

dam_ton_plot <- ggplot(data = warm) +
  geom_point(aes(x=year, y=dam_ton)) +
  theme_bw()

q2_patched <- (dam_base_plot + dam_pulse_plot) / (dam_diff_plot + dam_ton_plot)

q2_patched
```

```{r}
#Question 3
warm <- warm %>%
  mutate(scc1 = dam_diff/ (1+0.01)^X,
         scc2 = dam_diff/ (1+0.02)^X,
         scc3 = dam_diff/ (1+0.03)^X,
         scc4 = dam_diff/ (1+0.04)^X,
         scc5 = dam_diff/ (1+0.05)^X) %>% 
  mutate(scc1_sum = sum(scc1),
         scc2_sum = sum(scc2),
         scc3_sum = sum(scc3),
         scc4_sum = sum(scc4),
         scc5_sum = sum(scc5))

scc_df <- data.frame(c(0.01, 0.02, 0.03, 0.04, 0.05)) %>% 
  cbind(c(warm$scc1_sum[1], warm$scc2_sum[1], warm$scc3_sum[1], warm$scc4_sum[1], warm$scc5_sum[1]))

colnames(scc_df) <- c("rate", "scc_sum")

scc_plot <- ggplot(data = scc_df) +
  geom_point(aes(x=rate, y=scc_sum)) +
  theme_bw()

scc_plot
```

```{r}
#Question 4
rams <- 0.001+(2*0.01)

warm <- warm %>%
  mutate(sccrams = dam_diff/ (1+rams)^X) %>% 
  mutate(sccrams_sum = sum(sccrams))

sccrams_df <- data.frame(c(0.01, 0.02, 0.03, 0.04, 0.05, rams)) %>% 
  cbind(c(warm$scc1_sum[1], warm$scc2_sum[1], warm$scc3_sum[1], warm$scc4_sum[1], warm$scc5_sum[1], warm$sccrams_sum[1]))

colnames(sccrams_df) <- c("rate", "scc_sum")

rams_pt <- subset(sccrams_df, rate == 0.021)

scc_plotq4 <- ggplot(data = sccrams_df) +
  geom_point(aes(x=rate, y=scc_sum)) +
  geom_point(data = rams_pt, aes(x=rate, y=scc_sum), color = "red") +
  theme_bw()

scc_plotq4
```





